apiVersion: apps/v1
kind: Deployment
metadata:
  name: demojava_1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demojava
  template:
    metadata:
      labels:
        app: demojava
    spec:
      containers:
      - name: demojava
        image:venkat7624/demojava:latest
        ports:
        - containerPort: 8080

