apiVersion: v1
kind: Service
metadata:
  name: demojava
spec:
  type: NodePort
  selector:
    app: demojava
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32333 

